## Numpy Introduction
NumPy (Numerical Python)

In [4]:
import numpy as np

## Terminology

#### What is Array
adalah struktur data central dari perpustakaan numpy.

In [2]:
# cara dapat menginisialisasi array NumPy adalah dari nested Python Lists
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [3]:
# mengakses elemen dalam array menggunakan kurung siku
print(a[0])

[1 2 3 4]


ndaarray(N-dimensional array) yang digunakan untuk mempresentasikan matriks dan vektor. Vektor adalah array dengan satu kolom, sedangkan matriks adalah array dengan banyak kolom.

## Array

### Creating array

In [ ]:
np.array() #untuk membuat array numpy
np.zeros()
np.ones()
np.empty()
np.arange()

In [7]:
#contoh
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [8]:
#membuat array yang berisi 0
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [9]:
#membuat array yang berisi 1
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [10]:
#membuat array yang kosong, yang mana akan diisi dengan nilai random
np.empty(6)

array([1., 1., 1., 1., 1., 1.])

In [12]:
#membuat array dengan range dari element
print(np.arange(4))
print(np.arange(0,10,2)) #start,stop,step

[0 1 2 3]
[0 2 4 6 8]


In [13]:
np.arange(2,29,5)

array([ 2,  7, 12, 17, 22, 27])

### Add, remove and sort

In [ ]:
np.append()
np.delete()
np.sort()

In [14]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
np.append(arr, [1,2]) #menambahkan elemen ke array arr

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

In [16]:
#menghapus element array menggunakan np.delete()
np.delete(arr, 1)

array([1, 3, 4, 5, 6, 7, 8])

In [19]:
#mengurutkan angka elemen dalam array menggunakan np.sort()
cth = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(cth) #mengurutkan dengan urutan naik

array([1, 2, 3, 4, 5, 6, 7, 8])

### Shape and size

In [ ]:
ndarray.ndim() #untuk memberi tahu jumlah axes, atau dimensi dari array
ndarray.size() #untuk mengetahui jumlah total elemen array
ndarray.shape() #menampilkan tupple integer yang disimpan di array. Misal array 2 dimensi dengan 2 baris dan 3 kolom, maka bentuknya adalah (2,3)

In [21]:
# contoh
example = np.array([[[0, 1, 2, 3],
                     [4, 5, 6, 7]],
                    
                    [[0, 1, 2, 3],
                     [4, 5, 6, 7]],
                    
                    [[0, 1, 2, 3],
                     [4, 5, 6, 7]]])

print(example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [22]:
example.ndim #menampilkan dimensi array

3

In [23]:
example.size #menampilkan total element array

24

In [24]:
example.shape #menampilkan total element array

(3, 2, 4)

In [26]:
example_one = np.array([[0, 1, 2, 3]])
example_one.ndim

2

In [27]:
example_one.size

4

In [28]:
example_one.shape

(1, 4)

### Reshape

In [ ]:
np.reshape() akan memberikan bentuk baru ke array tanpa mengubah datanya

In [31]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [32]:
b = a.reshape(3,2) #mengubah bentuk array ke 3 kolom 2 baris
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [35]:
a.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

### Convert 1D to 2D

In [ ]:
np.newaxis #akan meningkatkan dimensi array sebesar satu dimensi
np.expand_diws 
#kedua fungsi tersebut untuk meningkatkan dimensi array

In [37]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [39]:
# menggunakan np.newaxis untuk menambahkan axis baru
a2 = a[np.newaxis]
print(a2.shape)
print(a2)

(1, 6)
[[1 2 3 4 5 6]]


### Indexing and Slicing

In [41]:
data = np.array([1,2,3])

print(data)
print(data[0])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

[1 2 3]
1
2
[1 2]
[2 3]
[2 3]


In [43]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [44]:
print(a[a>=5])

[ 5  6  7  8  9 10 11 12]


In [45]:
five_up = (a >= 5)
print(a[five_up])
print(a[a>=5])

[ 5  6  7  8  9 10 11 12]
[ 5  6  7  8  9 10 11 12]


In [46]:
# You can select elements that are divisible by 2
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [47]:
# you can select elements that satisfy two conditions using the & and | operators
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


### Creating Array from Existing Data

slicing indexing
np.vstack()
np.hstack()
np.hsplit()
.view()
.copy()

In [48]:
#membuat array baru dari bagian array mana saja dengan menentukan dimana akan di slice
cth = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
cth1 = cth[3:8]
cth1

array([4, 5, 6, 7, 8])

In [49]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [50]:
b = a.view()
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [51]:
c = a.copy()
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### Basic array operations

In [ ]:
data - ones
data * data
data / data

In [52]:
a = np.arange(3)
b = np.arange(4,7)
print(a)
print(b)

# basic array operations 
print(a + b)
print(a - b)
print(a * b)
print(a / b)

[0 1 2]
[4 5 6]
[4 6 8]
[-4 -4 -4]
[ 0  5 12]
[0.         0.2        0.33333333]


In [55]:
a.sum() #menjumlahkan semua elemen dalam array

3

In [61]:
c = np.array([[1,1],[2,2]])
c

array([[1, 1],
       [2, 2]])

In [63]:
c.sum(axis=0) #menjumlahkan baris

array([3, 3])

In [64]:
c.sum(axis=1) #menjumlahkan kolom

array([2, 4])

### Broadcasting
yaitu melakukan operasi antara array dengan satu bilangan (operasi antara vektor dan skalar)

### More array operations

In [ ]:
data.max()
data.min()
data.sum()

In [65]:
s = np.arange(20)
s

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [68]:
s.sum() #menjumlahkan element array

190

In [69]:
s.min() #nilai terkecil dari element

0

In [70]:
s.min(axis=0)

0

In [71]:
s.max()

19

In [72]:
s.max(axis=0)

19

In [73]:
s.std()

5.766281297335398

### Matrices

#### Creating matrices

In [74]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [75]:
print(np.ones((6,2)))
print(np.zeros((6,2)))
print(np.random.random((6,2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[0.10162449 0.29191415]
 [0.52957426 0.10320807]
 [0.12686464 0.40697598]
 [0.27288647 0.40493494]
 [0.29719718 0.74101218]
 [0.98938217 0.27130275]]


#### Matrix arithmetic

In [77]:
r = np.array([[8, 9], [14, 21]])
r

array([[ 8,  9],
       [14, 21]])

In [78]:
t = np.array([[27, 29], [41, 77]])
t

array([[27, 29],
       [41, 77]])

In [79]:
r + t

array([[35, 38],
       [55, 98]])

#### Dot product

In [80]:
a1 = np.array([[0,1],[4,5], [7,8]])
print(a1)
a2 = np.array([[0,1,2],[4,5,6]])
print(a2)

[[0 1]
 [4 5]
 [7 8]]
[[0 1 2]
 [4 5 6]]


In [81]:
np.dot(a1, a2)

array([[ 4,  5,  6],
       [20, 29, 38],
       [32, 47, 62]])

#### Matrix indexing

In [82]:
# slicing matrix
a1 = np.array([[1,2],[3,4], [5,6]])
print(a1)
print(a1[0])
print(a1[2])
print(a1[0:2])
print(a1[0,1])
print(a1[0][1])

[[1 2]
 [3 4]
 [5 6]]
[1 2]
[5 6]
[[1 2]
 [3 4]]
2
2


#### Matrix aggregation
menjumlahkan matriks dengan cara yang sama seperti menjumlahkan vektor

In [86]:
print(a1)

[[1 2]
 [3 4]
 [5 6]]


In [88]:
print(a1.max())
print(a1.min())
print(a1.sum())

6
1
21


In [89]:
print(a1.max(axis=0))
print(a1.max(axis=1))

[5 6]
[2 4 6]


#### Transporting and reshaping

In [90]:
a1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [92]:
a1.shape

(3, 2)

In [93]:
a1.T

array([[1, 3, 5],
       [2, 4, 6]])

In [96]:
a1.T.shape

(2, 3)

#### N-dimensional array

In [97]:
np.ones((6,5,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [98]:
np.zeros((6,5,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [99]:
np.random.random((6,5,2))

array([[[0.59090379, 0.5447575 ],
        [0.74887771, 0.30388218],
        [0.94658014, 0.78789952],
        [0.61763748, 0.96358487],
        [0.68944992, 0.78389583]],

       [[0.30209295, 0.73164655],
        [0.71883897, 0.96310281],
        [0.06161275, 0.60271296],
        [0.86084854, 0.49911857],
        [0.30482861, 0.96861397]],

       [[0.72097181, 0.02723478],
        [0.55302502, 0.1543775 ],
        [0.70150075, 0.20378465],
        [0.19166654, 0.01712785],
        [0.42872839, 0.77713263]],

       [[0.85080369, 0.65938041],
        [0.63690788, 0.9026582 ],
        [0.35647882, 0.80836504],
        [0.69938273, 0.63884108],
        [0.99328858, 0.16814768]],

       [[0.97927107, 0.24213309],
        [0.95212097, 0.94605976],
        [0.31497271, 0.70974912],
        [0.99261422, 0.02006481],
        [0.3038051 , 0.55215133]],

       [[0.20824013, 0.61975004],
        [0.06010296, 0.30102255],
        [0.57316291, 0.90537283],
        [0.40324267, 0.57110654],
    

#### Flatten N-dimensional array

In [104]:
z = np.arange(22)
z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21])

In [108]:
z = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
z

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [110]:
z1 = z.flatten()
z1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [113]:
z2 = z.ravel()
z2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])